### ISSUE TITLE
腾讯WE邀请函日程安排长页面浏览完再切页效果如何实现

### ISSUE THREAD

**Issue by kalechao87** [hahnzhu/parallax.js#11]
请问，WE案例，其中日程安排是一个长页面，滑动此页必须翻到长页面底部才能切页，请问这种页面在此插件下如何实现，谢谢！

**Comment by hahnzhu** [comment]
这个内部滚动是自己写的，鉴于大家都有此种需求，新版会考虑加上。年后会有新版本发布。

**Comment by kalechao87** [comment]
感谢回复，期待新版本。请问在此框架下实现内部滚动的原理当前有无参考、推荐文章，想先了解学习下~

**Comment by hahnzhu** [comment]
详见最后一页：http://hahnzhu.sinaapp.com/demo/140825_dazhaxie/html/index.html

**Comment by kalechao87** [comment]
非常感谢！
