### ISSUE TITLE
发现几个小问题

### ISSUE THREAD

**Issue by diamont1001** [hahnzhu/parallax.js#12]
目前发现了几个问题：

1. resize后不会自动适应 
解决方法：
插件最后增加以下代码：
window.addEventListener("resize", function() {
var pageWidth = $(window).width(), // 获取手机屏幕宽度
pageHeight = $(window).height(); // 获取手机屏幕高度
$pageArr.css({ // 初始化 page 宽高
'width': pageWidth + 'px',
'height': pageHeight + 'px'
});
}, false);

2. 对于某些安卓机子Webview，第一次取屏幕大小会为0，所以在页面onload时增加延时1S再初始化插件，但插件会报异常。
解决方法：
$(window).on("load", function() {});这个消息响改成函数体allOnload()，并在init()函数里最后调用allOnload()

3. 在安卓系统上，快速上下滑动页面几次，可能会导致整个页面不见了的情况，必现。IOS暂时没发现问题。
解决方法：还在定位中，求作者大大帮忙解决，谢谢

**Comment by hahnzhu** [comment]
谢谢提供这几种场景。关于第三种情况，应该是 curPage 当前页获取失败了，解决办法就是翻页停止之后才能继续翻第二页，新版会考虑这几种情况以及修复 :+1:

**Comment by yanhaijing** [comment]
本次切换过程中 应该禁止切换，切换完成后在打开状态

**Comment by diamont1001** [comment]
嗯嗯，我也觉得，可以考虑“翻页停止之后才能继续翻第二页”。麻烦作者大大了^_^

**Comment by gatspy** [comment]
大大，2.0什么时候发布呢？

**Comment by hahnzhu** [comment]
@gatspy 大概在春节后，经过这段时间对大家反馈的整理以及自己实践后的思考，这次会有焕然一新的改变。敬请期待 ~

**Comment by gatspy** [comment]
等的好着急啊嘿嘿

**Comment by diamont1001** [comment]
等的好着急啊嘿嘿

**Comment by hahnzhu** [comment]
抱歉，由于该项目无法保证持续的更新，同时有非常多同类型的优秀插件出现，本项目不再维护，感谢大家的支持。相关插件推荐：

* [motion.js](https://github.com/tgideas/motion)
* [zepto.fullpage](https://github.com/yanhaijing/zepto.fullpage)


推荐下自家的组件库，目前正在全新改版：

* [FrozenUI](http://frozenui.github.io/)

**Comment by yanhaijing** [comment]
听到这个消息很震惊啊，竟然不再维护了

**Comment by hahnzhu** [comment]
@yanhaijing 平时没有什么时间，加上已经有很好的替代品了，也就不重复造轮子啦~

**Comment by yanhaijing** [comment]
嗯 有舍才有得，加油
