### ISSUE TITLE
问问，这个js有跳转到指定页面的事件吗？

### ISSUE THREAD

**Issue by zlart** [hahnzhu/parallax.js#15]
您好，看到你们的js。很好。可惜不再更新了。之前一直用 parallax.js 我遇到一个小问题，
点击一个按钮，如何跳转到指定的页面？。请问有类似的事件吗？
谢谢！

**Comment by hahnzhu** [comment]
这个不支持哦，抱歉了~ 
可以试试首页推荐的 motion.js
