### ISSUE TITLE
page内容过长无法scroll

### ISSUE THREAD

**Issue by goddyZhao** [hahnzhu/parallax.js#5]
首先谢谢你的parallax，我在使用的时候发现页面过长后无法scroll，不知道是否有提供这方面的支持，因为我看到你readme页面第二张图中貌似是可以scroll的，谢谢！

**Comment by hahnzhu** [comment]
抱歉，由于该项目无法保证持续的更新，同时有非常多同类型的优秀插件出现，本项目不再维护，感谢大家的支持。相关插件推荐：

* [motion.js](https://github.com/tgideas/motion)
* [zepto.fullpage](https://github.com/yanhaijing/zepto.fullpage)


推荐下自家的组件库，目前正在全新改版：

* [FrozenUI](http://frozenui.github.io/)
