### ISSUE TITLE
parallax.js v2.0 计划

### ISSUE THREAD

**Issue by hahnzhu** [hahnzhu/parallax.js#9]
1、全局：采用新架构
2、支持特性：
* -[ ] 支持滚动到某一页，上/下一页
* -[ ] 初始化时直接到某一页
* -[ ] 支持页面内部滚动（惯性减速停止/非惯性）
* -[x] 支持循环滑动
* -[x] 提供滑动禁用开关
* -[ ] 支持延时加载
* -[x] 支持滚动动画、滚动时间定制
* -[ ] 添加资源加载器
* -[ ] 增加新的内置动画（震动、放大缩小、反弹）尝试兼容 Animate.css
* -[ ] 支持自定义动画（可以用 data-animation 配置自己写的动画，增加更多的属性：play-state, infinite）
* -[ ] 提供更多事件接口（滑动前，滑动后）
* -[ ] 音乐播放

3、文件组织
* -[x] 提供压缩版 JS 和 CSS
* -[x] 提取 reset.css
* 提供 example 用例文件夹，全局 Demo 页

4、Bug fix：
* -[x] Zepto 宽度获取不正确（Nexus、小米、魅族）
* -[ ] 手指移出屏幕后捕获不到 touchend（无法归位）
* -[ ] 禁止快速滑动，避免 curPage 获取不正常

5、其他：
* 提供默认箭头+loading+资源加载样式及图片，样式独立为文件
* 去掉 isHeadOrTail 函数
*  -[x] 添加不被压缩去除的版权信息，便于使用者查找
* onchange 回调函数索引从1开始
* -[x] 宽高可自定义，页数可自定义
* -[x] README 文档有误（link）
* 通过 Releases 输出新版本
* -[x] 支持模块化加载
* -[x] 避免和另外一个 Parallax 发生冲突（Parallax 别名 P）

6、特殊场景：
* 页面可能是动态生成节点，每种用户角色显示的页面不一样，页面数也可以会不一样
* 页面可能会使用缩放（适配各种屏幕），考虑 resize 情况
* 可延时加载
* 多分辨率兼容方案
* 横竖屏提示

**Comment by gatspy** [comment]
2.0什么时候出来呢，很期待啊。

**Comment by hahnzhu** [comment]
@gatspy 会争取尽快升级的 :)

**Comment by gatspy** [comment]
嘿嘿，谢谢您的辛劳。

**Comment by jinglingzs** [comment]
页面一个元素淡入到指定位置后,如何设置5秒后从位置淡出?

**Comment by hahnzhu** [comment]
@jinglingzs 自己写个 CSS3 动画即可

**Comment by gatspy** [comment]
我激动的不行，看到一个小时前更新了，以为2.0来了呢呵呵

**Comment by xijige** [comment]
请问，能点击滑动到指定页吗？

**Comment by xijige** [comment]
parallax.js 1.0不能滚动到下一页吗？

**Comment by xijige** [comment]
试了一下，确实不好添加，下一页。
动画都和start,end有关。。

**Comment by hahnzhu** [comment]
@xijige 目前的实现方式没有考虑到滚动到指定页，2.0 版本会改实现方式。因为年底时间较少，下月应该该可以完成改版~

**Comment by udbmnm** [comment]
页面高度100%，如果有input键盘就会遮住文本域

**Comment by hahnzhu** [comment]
@udbmnm 能否提供个 Demo？

**Comment by yanhaijing** [comment]
https://github.com/yanhaijing/zepto.fullpage 可以看下这个

**Comment by tower1229** [comment]
期待2.0

**Comment by gatspy** [comment]
这个是不是不更新2.0呢？

**Comment by hahnzhu** [comment]
自己挖的坑，必须要填的哈。

2015 年这类多屏切换形式的 H5 应用已经遍地开花了，而且越来越多的需求溢出，我也发现了现在已经有很多款适合非技术人员使用的可视化制作工具，一条商业化的道路也越发明显。

不过，每个需求都是个性化的，虽然可视化工具比较傻瓜，也可以快速解决部分需求；但是涉及到个性化的定制，还是少不了插件的底层支撑。

最近一直在忙着公司官网的改版，所以把这一块落下了，期间断断续续在改进，上面也可以看到进度。我会尽量快得做好的，也希望能把平时工作中总结的经验分享给大家， cheers :)

**Comment by gatspy** [comment]
期待大大的2.0早日面世。

**Comment by robinma** [comment]
希望快些出来呀，你给个时间线吧

**Comment by hahnzhu** [comment]
抱歉，由于该项目无法保证持续的更新，同时有非常多同类型的优秀插件出现，本项目不再维护，感谢大家的支持。相关插件推荐：

* [motion.js](https://github.com/tgideas/motion)
* [zepto.fullpage](https://github.com/yanhaijing/zepto.fullpage)


推荐下自家的组件库，目前正在全新改版：

* [FrozenUI](http://frozenui.github.io/)

**Comment by yanhaijing** [comment]
这个计划写的不错，吸收一点进入https://github.com/yanhaijing/zepto.fullpage
